In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("check_data/2011-2012 Solar home electricity data v2.csv", skiprows=1)
df.head()

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
0,1,3.78,2076,CL,1/07/2011,1.250,1.250,1.250,0.625,0.219,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.063,NaN
1,1,3.78,2076,GC,1/07/2011,1.077,0.669,0.674,0.615,0.321,...,0.276,0.241,0.168,0.234,0.164,0.639,0.118,0.219,0.162,NaN
2,1,3.78,2076,GG,1/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,1,3.78,2076,CL,2/07/2011,1.238,1.244,1.194,0.000,0.888,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.075,NaN
4,1,3.78,2076,GC,2/07/2011,0.476,0.130,0.044,0.094,0.032,...,0.234,0.306,0.183,0.240,0.170,0.506,0.224,0.088,0.084,NaN

In [ ]:
# Filter to Customer 27
df_customer_27 = df[df['Customer'] == 27]
df_customer_27.head()

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
24522,27,1.5,2093,CL,1/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
24523,27,1.5,2093,GC,1/07/2011,0.063,0.103,0.086,0.151,0.173,...,0.929,0.794,0.863,0.839,0.846,0.652,0.644,0.363,0.228,NaN
24524,27,1.5,2093,GG,1/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
24525,27,1.5,2093,CL,2/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
24526,27,1.5,2093,GC,2/07/2011,0.217,0.253,0.207,0.253,0.208,...,0.391,0.660,0.736,0.769,0.867,0.759,0.705,0.276,0.102,NaN

In [13]:
# Print number of unique dates
print("Number of unique dates for Customer 27:", df_customer_27['date'].nunique())

Number of unique dates for Customer 27: 366

In [21]:
df = pd.read_csv("check_data/2012-2013 Solar home electricity data v2.csv", skiprows=1)
df.head()

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
0,1,3.78,2076,CL,1/07/2012,1.250,1.250,1.250,1.263,0.131,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.081,NaN
1,1,3.78,2076,GC,1/07/2012,0.855,0.786,0.604,0.544,0.597,...,0.374,0.447,0.549,0.136,0.288,0.181,0.651,0.090,0.068,NaN
2,1,3.78,2076,GG,1/07/2012,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,1,3.78,2076,CL,2/07/2012,1.250,1.250,1.125,0.000,0.925,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.069,NaN
4,1,3.78,2076,GC,2/07/2012,0.309,0.082,0.059,0.097,0.290,...,0.353,0.464,0.229,0.811,0.222,0.306,1.034,0.136,0.067,NaN

In [11]:
# Filter to Customer 293
df_customer_293 = df[df['Customer'] == 293]
df_customer_293.head()

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
261363,293,1.05,2290,CL,1/07/2012,1.781,0.650,0.000,0.000,0.000,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.781,NaN
261364,293,1.05,2290,GC,1/07/2012,0.183,0.177,0.193,0.185,0.176,...,2.949,3.202,3.64,2.917,3.402,3.353,2.007,0.817,0.463,NaN
261365,293,1.05,2290,GG,1/07/2012,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,NaN
261366,293,1.05,2290,CL,2/07/2012,1.788,0.350,0.000,0.000,0.000,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.813,NaN
261367,293,1.05,2290,GC,2/07/2012,0.155,0.219,0.201,0.173,0.209,...,0.274,0.388,0.89,0.870,0.900,0.811,0.919,0.722,0.418,NaN

In [15]:
for customer in [293, 2, 272, 187, 161, 248, 95, 284, 294, 68, 289]:
    df_customer = df[df['Customer'] == customer]
    print(f"Number of unique dates for Customer {customer}:", df_customer['date'].nunique())

Number of unique dates for Customer 293: 365
Number of unique dates for Customer 2: 284
Number of unique dates for Customer 272: 365
Number of unique dates for Customer 187: 365
Number of unique dates for Customer 161: 365
Number of unique dates for Customer 248: 365
Number of unique dates for Customer 95: 365
Number of unique dates for Customer 284: 365
Number of unique dates for Customer 294: 365
Number of unique dates for Customer 68: 365
Number of unique dates for Customer 289: 365

In [22]:
# Filter to Customer 2
df_customer_2 = df[df['Customer'] == 2]
df_customer_2.head()

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
1095,2,1.62,2259,CL,1/07/2012,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
1096,2,1.62,2259,GC,1/07/2012,0.167,0.108,0.119,0.150,0.109,...,0.261,0.295,0.294,0.284,0.223,0.285,0.208,0.244,0.254,NaN
1097,2,1.62,2259,GG,1/07/2012,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.006,0.000,0.000,NaN
1098,2,1.62,2259,CL,2/07/2012,0.000,0.000,0.000,0.000,0.000,...,1.308,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
1099,2,1.62,2259,GC,2/07/2012,0.110,0.109,0.123,0.131,0.134,...,0.323,1.181,0.786,0.326,0.264,0.329,0.282,0.212,0.122,NaN

In [23]:
# Iterate through file in folder check_data
for file in ["check_data/2010-2011 Solar home electricity data.csv",
             "check_data/2011-2012 Solar home electricity data v2.csv", 
             "check_data/2012-2013 Solar home electricity data v2.csv"]:
    df = pd.read_csv(file, skiprows=1)
    print(f"File: {file}")
    for customer in range(1, 301):
        df_customer = df[df['Customer'] == customer]
        if df_customer['date'].nunique() < 365:
            print(f"Customer {customer} has less than 365 unique dates.")
        #else:
            #print(f"Customer {customer} has 365 or more unique dates.")
# Check for customers with less than 365 unique dates

File: check_data/2010-2011 Solar home electricity data.csv
File: check_data/2011-2012 Solar home electricity data v2.csv
File: check_data/2012-2013 Solar home electricity data v2.csv
Customer 2 has less than 365 unique dates.